title: <p align="center"> Subhash Reddy </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  
  
  <br>   
  Im getting trained on Machone learning course
  <br>
  </p>



theme: jekyll-theme-minimal
